# Site settings
title:       Miroslav Popovic
email:       contact@miroslavpopovic.com
author:      Miroslav Popovic
description: "A somewhat independent web and .NET development consultant, currently employed at Abacus Solutions & Consulting."
baseurl:     ""
url:         "http://blog.miroslavpopovic.com"

# Google analytics
google_analytics: UA-32542962-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: miroslavpopovic

# Social icons
feed_url: http://feeds.feedburner.com/miroslavpopovic/blog
show_social_icons: true
github_username: miroslavpopovic
stackoverflow_id: 119230
twitter_username: miroslavpopovic
google_plus_id: +MiroslavPopovic
linkedin_username: miroslavpopovic
codeproject_username: Miroslav-Popovic
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share: '
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: true
share_tumblr: true
share_reddit: true
share_stumbleupon: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     5
sass:
  compressed: true
